#!/usr/bin/env bash

if [ ! -f "/home/yaros/.config/winapps/winapps.conf" ] && [ ! -f "/home/yaros/.winapps" ]; then
	echo "You need to create a ~/.config/winapps/winapps.conf configuration. Exiting..."
	exit
fi

DIR="$(dirname "$(readlink -f "$0")")"
RUN="$(date)-${RANDOM}"

if [ ! -d "/home/yaros/.local/share/winapps" ]; then
	mkdir -p "/home/yaros/.local/share/winapps"
fi

RDP_SCALE=100

if [ -f "/home/yaros/.config/winapps/winapps.conf" ]; then
	. "/home/yaros/.config/winapps/winapps.conf"
else
	. "/home/yaros/.winapps"
fi

function dprint() {
	if [ "${DEBUG}" = "true" ]; then
		echo "[${RUN}] ${1}" >> "/home/yaros/.local/share/winapps/winapps.log"
	fi
}

dprint "START"

if [ -f "/home/yaros/.local/share/winapps/run" ]; then
	LAST_RAN=$(stat -t -c %Y "/home/yaros/.local/share/winapps/run")
	dprint "LAST_RAN:${LAST_RAN}"
	touch "/home/yaros/.local/share/winapps/run"
	THIS_RUN=$(stat -t -c %Y "/home/yaros/.local/share/winapps/run")
	dprint "THIS_RUN:${THIS_RUN}"
	if (( $THIS_RUN - $LAST_RAN < 2 )); then
		exit
	fi
else
	touch "/home/yaros/.local/share/winapps/run"
fi

if [ -z "$(which xfreerdp)" ]; then
	echo "You need xfreerdp!"
	echo "  sudo apt-get install -y freerdp2-x11"
	exit
fi

if [ -z "${RDP_IP}" ]; then
	if [ -z "$(groups |grep libvirt)" ]; then
		echo "You are not a member of the libvirt group. Run the below then reboot."
		echo '  sudo usermod -a -G libvirt $(whoami)'
		echo '  sudo usermod -a -G kvm $(whoami)'
		exit
	fi
	if [ -z "$(virsh list |grep RDPWindows)" ]; then
		echo "RDPWindows is not running, run:"
		echo "  virsh start RDPWindows"
		exit
	fi
	RDP_IP=$(virsh net-dhcp-leases default |grep RDPWindows |awk '{print $5}')
	RDP_IP=${RDP_IP%%\/*}
fi

dprint "1:${1}"
dprint "2:${2}"
dprint "@:${@}"

MULTI_FLAG="span"
if [ "${MULTIMON}" = "true" ]; then
	MULTI_FLAG="multimon"
fi

if [ "${1}" = "windows" ]; then
	xfreerdp ${RDP_FLAGS} /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} /scale:${RDP_SCALE} /dynamic-resolution +clipboard +auto-reconnect +home-drive /wm-class:"Microsoft Windows" 1> /dev/null 2>&1 &
elif [ "${1}" = "check" ]; then
	dprint "CHECK"
	xfreerdp ${RDP_FLAGS} /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +clipboard +home-drive -wallpaper /scale:${RDP_SCALE} /dynamic-resolution /${MULTI_FLAG} /app:"explorer.exe"
elif [ "${1}" = "manual" ]; then
	dprint "MANUAL:${2}"
	xfreerdp ${RDP_FLAGS} /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +home-drive +clipboard -wallpaper /scale:${RDP_SCALE} /dynamic-resolution /${MULTI_FLAG} /app:"${2}" 1> /dev/null 2>&1 &
elif [ "${1}" != "install" ]; then
	dprint "DIR:${DIR}"
	if [ -e "${DIR}/../apps/${1}/info" ]; then
		. "${DIR}/../apps/${1}/info"
		ICON="${DIR}/../apps/${1}/icon.svg"
	elif [ -e "/home/yaros/.local/share/winapps/apps/${1}/info" ]; then
		. "/home/yaros/.local/share/winapps/apps/${1}/info"
		ICON="/home/yaros/.local/share/winapps/apps/${1}/icon.svg"
	elif [ -e "/usr/local/share/winapps/apps/${1}/info" ]; then
		. "/usr/local/share/winapps/apps/${1}/info"
		ICON="/usr/local/share/winapps/apps/${1}/icon.svg"
	else
		echo "You need to run 'install.sh' first."
		exit 1
	fi
	if [ -n "${2}" ]; then
		dprint "HOME:/home/yaros"
		FILE=$(echo "${2}" | sed 's|'"/home/yaros"'|\\\\tsclient\\home|;s|/|\\|g;s|\\|\\\\|g')
		dprint "FILE:${FILE}"
		xfreerdp ${RDP_FLAGS} /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +clipboard +home-drive -wallpaper /scale:${RDP_SCALE} /dynamic-resolution /${MULTI_FLAG} /wm-class:"${FULL_NAME}" /app:"${WIN_EXECUTABLE}" /app-icon:"${ICON}" /app-cmd:"\"${FILE}\"" 1> /dev/null 2>&1 &
	else
		xfreerdp ${RDP_FLAGS} /d:"${RDP_DOMAIN}" /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} +auto-reconnect +clipboard +home-drive -wallpaper /scale:${RDP_SCALE} /dynamic-resolution /${MULTI_FLAG} /wm-class:"${FULL_NAME}" /app:"${WIN_EXECUTABLE}" /app-icon:"${ICON}" 1> /dev/null 2>&1 &
	fi
fi

dprint "END"
