# Shell variables
# Generated by 'wal'
wallpaper='/home/yaros/shared/Wallpapers/131.jpg'

# Special
background='#0e1524'
foreground='#cfd7e8'
cursor='#cfd7e8'

# Colors
color0='#0e1524'
color1='#4A73B2'
color2='#4874BB'
color3='#917085'
color4='#6285BA'
color5='#6992CA'
color6='#98AEDA'
color7='#cfd7e8'
color8='#9096a2'
color9='#4A73B2'
color10='#4874BB'
color11='#917085'
color12='#6285BA'
color13='#6992CA'
color14='#98AEDA'
color15='#cfd7e8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
