--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/yaros/shared/Wallpapers/299.jpg"

-- Special
background="#0a0312"
foreground="#91cdc9"
cursor="#91cdc9"

-- Colors
color0="#0a0312"
color1="#9C2463"
color2="#CA2E60"
color3="#A1545A"
color4="#E45B62"
color5="#F4AA67"
color6="#39508B"
color7="#91cdc9"
color8="#658f8c"
color9="#9C2463"
color10="#CA2E60"
color11="#A1545A"
color12="#E45B62"
color13="#F4AA67"
color14="#39508B"
color15="#91cdc9"
