# Shell variables
# Generated by 'wal'
wallpaper='/home/yaros/shared/Wallpapers/299.jpg'

# Special
background='#0a0312'
foreground='#91cdc9'
cursor='#91cdc9'

# Colors
color0='#0a0312'
color1='#9C2463'
color2='#CA2E60'
color3='#A1545A'
color4='#E45B62'
color5='#F4AA67'
color6='#39508B'
color7='#91cdc9'
color8='#658f8c'
color9='#9C2463'
color10='#CA2E60'
color11='#A1545A'
color12='#E45B62'
color13='#F4AA67'
color14='#39508B'
color15='#91cdc9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
