--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/yaros/shared/Wallpapers/131.jpg"

-- Special
background="#0e1524"
foreground="#cfd7e8"
cursor="#cfd7e8"

-- Colors
color0="#0e1524"
color1="#4A73B2"
color2="#4874BB"
color3="#917085"
color4="#6285BA"
color5="#6992CA"
color6="#98AEDA"
color7="#cfd7e8"
color8="#9096a2"
color9="#4A73B2"
color10="#4874BB"
color11="#917085"
color12="#6285BA"
color13="#6992CA"
color14="#98AEDA"
color15="#cfd7e8"
