#0a0312

$foreground = rgb(91cdc9)
$background = rgb(0a0312)
$wallpaper = rgb(home/yaros/shared/Wallpapers/299.jpg)

$color0 = rgb(0a0312)
$color1 = rgb(9C2463)
$color2 = rgb(CA2E60)
$color3 = rgb(A1545A)
$color4 = rgb(E45B62)
$color5 = rgb(F4AA67)
$color6 = rgb(39508B)
$color7 = rgb(91cdc9)
$color8 = rgb(658f8c)
$color9 = rgb(9C2463)
$color10 = rgb(CA2E60)
$color11 = rgb(A1545A)
$color12 = rgb(E45B62)
$color13 = rgb(F4AA67)
$color14 = rgb(39508B)
$color15 = rgb(91cdc9) 