foreground   #91cdc9
background   #0a0312
cursor       #91cdc9

color0       #0a0312
color8       #658f8c
color1       #9C2463
color9       #9C2463
color2       #CA2E60
color10      #CA2E60
color3       #A1545A
color11      #A1545A
color4       #E45B62
color12      #E45B62
color5       #F4AA67
color13      #F4AA67
color6       #39508B
color14      #39508B
color7       #91cdc9
color15      #91cdc9
