[General]
lastDisplay=0
maximizedWindow=true
savedPaths=/home/yaros, /home/yaros, /home/yaros, /home/yaros, /home/yaros, /home/yaros, /home/yaros, /home/yaros, /home/yaros
windowGeometry=@Rect(0 0 960 1043)
