[FileDialog]
history=file:///home/yaros/Videos/recordings, file:///home/yaros/.config/dunst, file:///run/media/yaros/Lexar/Oct 24 Lviv, file:///home/yaros/Downloads, file:///home/yaros/shared
lastVisited=file:///home/yaros/shared
qtVersion=5.9.9
shortcuts=file:, file:///home/yaros
sidebarWidth=70
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xec\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xff\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
